#!/bin/bash
#PBS -N file_sync_wcoss2               
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
##PBS -q dev
#PBS -A NAEFS-DEV
#PBS -l walltime=00:15:00
#PBS -l select=1:ncpus=1:mem=1GB
##PBS -l debug=true

COM_d=/lfs/h2/emc/vpppg/noscrub/bo.cui 
COM_c=/lfs/h2/emc/ptmp/bo.cui              

subdirlist="ecf ecf_prod scripts run_check_para_v7 sorc jobs docs ush versions grads "
subdirlist="ecf          scripts run_check_para_v7      jobs docs ush versions grads "
#subdirlist="scripts"
dir=naefs.v7.0.0

# sync dogwood  to cactus
for subdir in $subdirlist; do
  rsync -avzh $COM_c/$dir/$subdir bo.cui@ddxfer.wcoss2.ncep.noaa.gov:$COM_d/$dir
done

