SHELL=  /bin/sh
CMD=	/global/save/wx20cb/NUOPC_2012/exec/rtma_crps_from_avgspr        
FC=     xlf_r
FOPTS=  -qsmp=noauto
LOPTS=
INCS=
SRCS=	rtma_crps_from_avgspr.f90 CRPS.f90 CRPS_WDIR.f90 SORTMM.f90 QUANOR.f QUASTN.f QUASTN.f QUANOR.f 
LIBS=   /nwprod/lib/libbacio_4.a \
        /nwprod/lib/libw3_4.a \
        /nwprod/lib/libip_4.a \
        /nwprod/lib/libsp_4.a \
        -l essl
$(CMD): $(SRCS)
	$(FC) $(FOPTS) $(SRCS) $(LIBS) -o $(CMD)
vrfy0:	$(SRCS)
	$(FC) $(FOPTS) $(SRCS) /nwprod/w3lib90/iplib_4_604 $(LIBS) -o vfprob
