SHELL=	/bin/sh
LIBS=   -L/nwprod/lib/ -lbacio_4 -lw3_4 -lbufr_4_32 -lip_4 -lsp_4
SRCS=	naefs_crps_avg.f90                              
CMD=	/global/save/wx20cb/Verification/exec/naefs_crps_avg
FC=	ncepxlf90
FFLAGS=	-O3 -qsuffix=f=f90 -qlist -qsource -qlanglvl=90PURE -bnoquiet 
#FFLAGS=	-O3 -qsuffix=f=f90 -qlist -qsource -bnoquiet 

$(CMD):	$(SRCS)
	$(FC) $(SRCS) $(FFLAGS) -o $(@) $(OBJS) $(LIBS)
